features/urls.py
# Author - Matt Andrzejczuk
from django.urls import path

from features import views

app_name = "features"
urlpatterns = [
    path('', views.AskQuestionView.as_view(), name='index'),
    path('ask', views.AskQuestionView.as_view(), name='ask'),
    path('q/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
    path('daily/<int:year>/<int:month>/<int:day>/',
         views.DailyQuestionList.as_view(),
         name='daily_questions'),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from features import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('features.urls', namespace='features')),
    path('security/', include('security.urls', namespace='user')),
    path('q/<int:pk>/answer', views.CreateAnswerView.as_view(), name='answer_question'),
    path('a/<int:pk>/accept', views.UpdateAnswerAcceptance.as_view(), name='update_answer_acceptance'),
]

features/models.py
from django.db import models
from django.conf import settings
from django.urls.base import reverse
# Create your models here.


class Question(models.Model):
    title = models.CharField(max_length=140)
    question = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('questions:question _detail', kwargs={'pk': self.id})

    def can_accept_answers(self, user):
        return user == self.user


class Answer(models.Model):
    answer = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(to=Question,
                                 on_delete=models.CASCADE)
    accepted = models.BooleanField(default=True,
                                   help_text="Author of question marks this as answered.")

    class Meta:
        ordering = ('-created', )

features/models/answer_data.py
from django.db import models
from django.conf import settings
from django.urls.base import reverse



class Question(models.Model):
    title = models.CharField(max_length=140)
    question = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('features:question_detail', kwargs={'pk': self.id})

    def can_accept_answers(self, user):
        return user == self.user


class Answer(models.Model):
    answer = models.TextField()
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(to=Question,
                                 on_delete=models.CASCADE)
    accepted = models.BooleanField(default=True,
                                   help_text="Author of question marks this as answered.")

    class Meta:
        ordering = ('-created',)

features/models/question_data.py
from django.db import models
from django.conf import settings
from django.urls.base import reverse


# Create your models here.

features/forms.py
# Author - Matt Andrzejczuk
from django import forms
from django.contrib.auth import get_user_model

from features.models import Question



class QuestionForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True,
    )

    class Meta:
        model = Question
        fields = ['title', 'question', 'user', ]

features/routes/question_urls.py
# Author - Matt Andrzejczuk

# from django.urls.conf import path
from django.urls import path

from features import views

app_name = "features"
urlpatterns = [
    path('ask', views.AskQuestionView.as_view(), name='ask'),
    path('q/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
    path('daily/<int:year>/<int:month>/<int:day>/',
         views.DailyQuestionList.as_view(),
         name='daily_questions'),
]

features/views.py
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView

from features.forms import QuestionForm
from features.models import Question


class AskQuestionView(LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    template_name = 'features/ask.html'

    def get_initial(self):
        return {
            'user': self.request.user.id
        }

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            return super().form_valid(form)
        elif action == 'PREVIEW':
            preview = Question(
                question=form.cleaned_data['question'],
                title=form.cleaned_data['title']
            )
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()

features/views/answer_acceptance.py
# Author - Matt Andrzejczuk

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView
from django.http import HttpResponseRedirect

from features.posts.answer_forms import AnswerAcceptanceForm
from features.models.answer_data import Answer



class UpdateAnswerAcceptance(LoginRequiredMixin, UpdateView):
    form_class = AnswerAcceptanceForm
    queryset = Answer.objects.all()

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_invalid(self, form):
        return HttpResponseRedirect(
            redirect_to=self.object.question.get_absolute_url()
        )

features/views/answer_create.py
# Author - Matt Andrzejczuk

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.http import HttpResponseBadRequest

from features.models import Question
from features.posts import AnswerForm


class CreateAnswerView(LoginRequiredMixin, CreateView):
    form_class = AnswerForm
    template_name = 'features/create_answer.html'

    def get_initial(self):
        return {
            'question': self.get_question().id,
            'user': self.request.user.id,
        }

    def get_context_data(self, **kwargs):
        return super().get_context_data(question=self.get_question(),
                                        **kwargs)

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            #save and redirect as usual.
            return super().form_valid(form)
        elif action == 'PREVIEW':
            ctx = self.get_context_data(preview=form.cleaned_data['answer'])
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()

    def get_question(self):
        return Question.objects.get(pk=self.kwargs['pk'])

features/views/base_views.py
# Author - Matt Andrzejczuk


from django.http import HttpResponse
from django.template import loader




def home_page(request):
    template = loader.get_template("index.html")
    visitor = request.META
    context = {"visitor": visitor}
    return HttpResponse(template.render(context))

features/views/question_create.py
# Author - Matt Andrzejczuk
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView

from features.posts import QuestionForm
from features.models import Question


class AskQuestionView(LoginRequiredMixin, CreateView):
    form_class = QuestionForm
    template_name = 'features/ask.html'

    def get_initial(self):
        return {
            'user': self.request.user.id
        }

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == 'SAVE':
            return super().form_valid(form)
        elif action == 'PREVIEW':
            preview = Question(
                question=form.cleaned_data['question'],
                title=form.cleaned_data['title']
            )
            ctx = self.get_context_data(preview=preview)
            return self.render_to_response(context=ctx)
        return HttpResponseBadRequest()

features/views/question_detail.py
# Author - Matt Andrzejczuk
from django.views.generic import DetailView

from features.posts import AnswerForm, AnswerAcceptanceForm
from features.models import Question


class QuestionDetailView(DetailView):
    model = Question

    ACCEPTANCE_FORM = AnswerAcceptanceForm(initial={'accepted': True})
    REJECT_FORM = AnswerAcceptanceForm(initial={'accepted': False})

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update({
            'answer_form': AnswerForm(initial={
                'user': self.request.user.id,
                'question': self.object.id,
            })
        })
        if self.object.can_accept_answers(self.request.user):
            ctx.update({
                'accept_form': self.ACCEPTANCE_FORM,
                'reject_form': self.REJECT_FORM,
            })
        return ctx

features/views/question_list.py
# Author - Matt Andrzejczuk

from django.views.generic import DayArchiveView, RedirectView
from django.urls import reverse
from features.models import Question
from django.utils import timezone


class DailyQuestionList(DayArchiveView):
    queryset = Question.objects.all()
    date_field = 'created'
    month_format = '%m'
    allow_empty = True


class TodaysQuestionList(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        today = timezone.now()
        return reverse(
            'questions:daily_questions',
            kwargs={
                'day': today.day,
                'month': today.month,
                'year': today.year
            }
        )

templates/features/ask.html
{% extends "base.html" %}

{% load markdownify %}
{% load crispy_forms_tags %}

{% block title %} Ask a question {% endblock %}

{% block body %}
<div class="col-md-12">
    <h1>Ask a question</h1>
    {% if preview %}
        <div class="card question-preview">
            <div class="card-header">
                Question Preview
            </div>
            <div class="card-body">
                <h1 class="card-title">{{ preview.title }}</h1>
                {{ preview.question | markdownify }}
            </div>
        </div>
    {% endif %}

<form method="post">
    {{ form | crispy }}
    {% csrf_token %}
    <button class="btn btn-primary" type="submit" name="action" value="preview">
        Preview
    </button>
    <button class="btn btn-primary" type="submit" name="action" value="SAVE">
        Ask
    </button>
</form>
</div>
{% endblock %}

templates/features/create_answer.html
{% extends "base.html" %}

{% load markdownify %}

{% block body %}
    {% include 'features/common/display_question.html' %}
    {% if preview %}
        <div class="card question-preview">
            <div class="card-header">
                Answer Preview
            </div>
            <div class="card-body">
                {{ preview|markdownify }}
            </div>
        </div>
    {% endif %}
    {% include 'features/common/post_answer.html' with answer_form=form %}
{% endblock %}

templates/features/question_archive_day.html
{% extends "base.html" %}

{% block title %}
    Questions on {{ day }}
{% endblock %}

{% block body %}
<div class="col-sm-12">
    <h1>
        Highest Voted Questions of {{ day }}
    </h1>
    <ul>
        {% for question in object_list %}
            <li>
                {{ question.votes }}
                <a href="{{ question.get_absolute_url }}">
                    {{ question }}
                </a>
                by
                {{ question.user }}
                on {{ question.created }}
            </li>
        {% empty %}
            <li>Hmm... Everyone thinks they know everything today.</li>
        {% endfor %}
    </ul>
    <div>
        {% if previous_day %}
            <a href="{% url 'features:daily_questions' year=previous_day.year  month=previous_day.month day=previous_day.day %}">
                << Previous Day
            </a>
        {% endif %}
        {% if next_day %}
            <a href="{% url 'features:daily_questions' year=next_day.year month=next_day.month day=next_day.day %}">
                Next Day >>
            </a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/features/question_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ question.title }} - {{ block.super }}
{% endblock %}

{% block body %}
    {% include "features/common/display_question.html" %}
    {% include "features/common/list_answers.html" %}

    {% if user.is_authenticated %}
        {% include "features/common/question_post_answer.html" %}
    {% else %}
        <div>
            Login to post answers
        </div>
    {% endif %}
{% endblock %}