features/urls.py
# Author - Matt Andrzejczuk
from django.urls import path

from features import views

app_name = "features"
urlpatterns = [
    path('', views.AskQuestionView.as_view(), name='index'),
    path('ask', views.AskQuestionView.as_view(), name='ask'),
    path('q/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
    path('daily/<int:year>/<int:month>/<int:day>/',
         views.DailyQuestionList.as_view(),
         name='daily_questions'),
]

security/urls.py
# Author - Matt Andrzejczuk

from django.urls import path
from django.contrib.auth import views as auth_views

from security.views import RegisterView


app_name = "security"
urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name="login"),
    path('logout', auth_views.LogoutView.as_view(), name="logout"),
    path('register', RegisterView.as_view(success_url=""), name="register"),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from features import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('features.urls', namespace='features')),
    path('security/', include('security.urls', namespace='user')),
    path('q/<int:pk>/answer', views.CreateAnswerView.as_view(), name='answer_question'),
    path('a/<int:pk>/accept', views.UpdateAnswerAcceptance.as_view(), name='update_answer_acceptance'),
]

features/views/base_views.py
# Author - Matt Andrzejczuk


from django.http import HttpResponse
from django.template import loader




def home_page(request):
    template = loader.get_template("index.html")
    visitor = request.META
    context = {"visitor": visitor}
    return HttpResponse(template.render(context))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
</head>
<meta charset="UTF-8">
<title>{% block title %}Answerly{% endblock %}</title>
<link href="" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="/volatile/base.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/core.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/buttons.min.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/core.extras.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/dashicons.min.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/demo.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/flexslider.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/imgareaselect.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/media-views.min.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/mediaelementplayer.min.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/now-ui-kit.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/purple.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/style.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/woocommerce.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/woocommerce-layout.css">
<link rel="stylesheet" type="text/css" href="/volatile/styles/woocommerce-smallscreen.css">

<script src="/volatile/includes/jquery.js" type="text/javascript"></script>
<script src="/volatile/includes/popper.js" type="text/javascript"></script>
<script src="/volatile/includes/moment.js" type="text/javascript"></script>
<script src="/volatile/includes/nouislider.js" type="text/javascript"></script>
<script src="/volatile/includes/now-ui-kit.js" type="text/javascript"></script>
<script src="/volatile/includes/utils.js" type="text/javascript"></script>
<script src="/volatile/includes/chart.js" type="text/javascript"></script>
<script src="/volatile/includes/tether.js" type="text/javascript"></script>

<script src="/volatile/core/bootstrap.js" type="text/javascript"></script>
<script src="/volatile/core/datetimepicker.js" type="text/javascript"></script>
<script src="/volatile/core/selectpicker.js" type="text/javascript"></script>
<script src="/volatile/core/switch.js" type="text/javascript"></script>
<script src="/volatile/core/tagsinput.js" type="text/javascript"></script>
</head>


<body>
<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Answerly</a>
        <ul class="navbar-nav">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'features:ask' %}">
                    Ask
                </a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'features:index' %}">
                    Today's Question
                </a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'security:login' %}">Login</a>

                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'security:login' %}">Login</a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'security:register' %}">Register</a>

                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block body %}
    {% endblock %}
</div>
</body>


</html>

templates/index.html
{% extends "base.html" %}


{% block title %} Mod Overflow {% endblock %}